[package]
name = "stackoverflow_rust_api"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
tokio = {version="1", features = ["full"]}
axum = "0.7.4"
serde = { version = "1.0", features = ["derive"] }